package:
  name: pyocct2
  version: 7.8.0.0

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}          #  [win]
    - cmake
    - ninja
    - rapidjson
    - vtk * egl* # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxi-devel') }}       # [linux]
    - {{ cdt('libxext-devel') }}     # [linux]
    - python {{ python }}

  host:
    - python {{ python }}
    - pybind11
    - occt ==7.8.0
    - tbb-devel

  run:
    - python {{ python }}.*
    - occt ==7.8.0

test:
  source_files:
    - test

about:
  home: https://github.com/ovo-Tim/pyOCCT2
  license: LGPL2.1
  license_family: LGPL
  summary: Python bindings for OpenCASCADE.
  description: Python bindings for OpenCASCADE geometry kernel.
